Extending Columns
TappNetwork/filament-auditing pull request #1
Opened 2022-09-27 15:16 UTC by LogicSatinn

There are columns that somebody may want to be added to the Relation Manager without editing the component in the vendor folder. So this PR adds the ability to add columns they'd like to add to the Relation Manager via the config file.

2022-09-27 17:55 UTC, swilla requested changes
Thank you!  Can you add a section to the docs that details how to use this?

2022-09-27 19:43 UTC, LogicSatinn commented
> Thank you! Can you add a section to the docs that details how to use this?

Sure thing @swilla

2022-09-27 20:15 UTC, LogicSatinn commented
@swilla I have added the section to the docs. I hope it's clear and understandable enough.

2022-09-27 23:35 UTC, andreia requested changes
That's great, thank you @LogicSatinn for this contribution!

Something I noticed when testing:
I think this way (`\Filament\Tables\Columns\TextColumn::make('id')`) it's not allowed for serialization on config file.

When I run `php artisan optimize`, I get this message when caching the config files:

![artisan](https://user-images.githubusercontent.com/38911/192655440-acc8d891-53bb-4960-b374-7affd125c7fe.png)

You could use, for e.g., this way instead:

On config file:

```php
<?php

return [

    //...

    'audits_extend' => [
        'url' => \Filament\Tables\Columns\TextColumn::class,
        'ip_address' => \Filament\Tables\Columns\TextColumn::class,
    ]

];
```

On relation manager:

```php
    public static function table(Table $table): Table
    {
        $extraColumns = collect(config('filament-auditing.audits_extend'))->map(function ($columnClass, $columnName){
            return $columnClass::make($columnName);
        });

        return $table
            ->columns(Arr::flatten([
                Tables\Columns\TextColumn::make('user.name'),
                Tables\Columns\TextColumn::make('event'),
                Tables\Columns\TextColumn::make('created_at')
                    ->label('Created'),
                Tables\Columns\ViewColumn::make('old_values')
                    ->view('filament-auditing::tables.columns.key-value'),
                Tables\Columns\ViewColumn::make('new_values')
                    ->view('filament-auditing::tables.columns.key-value'),
                $extraColumns,
            ]))
            //...
```

2022-09-28 11:35 UTC, LogicSatinn commented
> That's great, thank you @LogicSatinn for this contribution!
> 
> Something I noticed when testing: I think this way (`\Filament\Tables\Columns\TextColumn::make('id')`) it's not allowed for serialization on config file.
> 
> When I run `php artisan optimize`, I get this message when caching the config files:
> 
> ![artisan](https://user-images.githubusercontent.com/38911/192655440-acc8d891-53bb-4960-b374-7affd125c7fe.png)
> 

😢Shoot ... I somehow missed that. And the solution you provided is genius. Let's see how we can make that happen.

2022-09-28 12:07 UTC, LogicSatinn commented
@andreia I'm concerned about the inability to chain table methods on the classes though. I'm trying to see if there's anything I can do about that.

2022-09-28 15:02 UTC, LogicSatinn commented
@andreia @swilla Things may not be clean as one would like but, I hope that does the work. If there's any other problem, ping @LogicSatinn .

2022-09-28 20:51 UTC, andreia approved these changes
Excellent, thank you!

2022-09-29 20:56 UTC, merged